version: '3.7'
services:
  p8_webapp:
    labels:
      # The "internal" setting uses Caddy's own internal CA so we don't bother
      # LetsEncrypt. See https://caddyserver.com/docs/caddyfile/directives/tls
      # for more details.
      caddy.tls: internal

  p8_api:
    ports:
      - 5000:5000
