version: '3.7'
services:
  p8_webapp:
    build: .
    image: ternandsparrow/pollin8-web-client:${P8_IMAGE_TAG:-dev}
    container_name: p8_web
    environment:
      API_BASE_URL: 'http://p8_api:5000'
      ROLLBAR_SERVER_TOKEN: ${ROLLBAR_SERVER_TOKEN}
      ROLLBAR_CLIENT_TOKEN: ${ROLLBAR_CLIENT_TOKEN}
      DEPLOYED_TO_ENV: ${DEPLOYED_TO_ENV}
      VIRTUAL_HOST: ${WEBAPP_PUBLIC_DNS}
      LETSENCRYPT_HOST: ${WEBAPP_PUBLIC_DNS}
    restart: unless-stopped
    labels:
      caddy: ${WEBAPP_PUBLIC_DNS}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    ports: # FIXME
      - ${P8_WEB_PORT:-3000}:3000 # only used when we aren't running behind nginx
    logging:
      driver: "json-file"
      options:
        max-size: 100m

  p8_api:
    image: ternandsparrow/natcap-invest-docker-flask:1.2.3_3.8.9
    container_name: p8_api
    environment:
      NIDF_ENV: production
      SOCKETIO_SECRET: ${SOCKETIO_SECRET}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 100m

  rev_proxy:
    image: lucaslorentz/caddy-docker-proxy:2.3-alpine
    container_name: p8_rev_proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - p8-caddy:/data
    labels:
      caddy.email: ${LETSENCRYPT_EMAIL}
    logging:
      driver: "json-file"
      options:
        max-size: 100m

volumes:
  p8-caddy:
