version: '3.7'
services:
  p8_webapp:
    build: .
    image: ternandsparrow/pollin8-web-client:${P8_IMAGE_TAG:-dev}
    container_name: p8_web
    init: true
    environment:
      API_BASE_URL: 'http://p8_api:5000'
      SENTRY_DSN: ${SENTRY_DSN_WEB:-}
      DEPLOYED_TO_ENV: ${DEPLOYED_TO_ENV}
      GA_ID: ${GA_ID}
    restart: unless-stopped
    labels:
      caddy: ${WEBAPP_PUBLIC_DNS}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    logging:
      driver: "json-file"
      options:
        max-size: 100m

  p8_api:
    image: ternandsparrow/natcap-invest-docker-flask:1.2.4_3.8.9
    container_name: p8_api
    init: true
    environment:
      NIDF_ENV: production
      SOCKETIO_SECRET: ${SOCKETIO_SECRET}
      CORS_ORIGIN: https://${WEBAPP_PUBLIC_DNS}
      SENTRY_DSN: ${SENTRY_DSN_API:-}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 100m

  rev_proxy:
    image: lucaslorentz/caddy-docker-proxy:2.3-alpine
    container_name: p8_rev_proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - p8-caddy:/data
    labels:
      caddy.email: ${LETSENCRYPT_EMAIL}
    logging:
      driver: "json-file"
      options:
        max-size: 100m

volumes:
  p8-caddy:
