AWSTemplateFormatVersion: 2010-09-09
Parameters:
  envlevel:
    Type: String
    AllowedValues:
      - dev.
      - test.
      - PROD
  theregion:
    Type: String
    Default: us-west-1
Conditions: 
  IsProd: !Equals [ !Ref envlevel, PROD ]
Resources:
  cfdistro:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - !Join ['', [www., !If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], pollin8.org.au]]
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false # maybe we do need this for Angular to work
          TargetOriginId: !Join ['', [S3-Website-www., !If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], pollin8.org.au, .s3-website-, Ref: theregion, .amazonaws.com]]
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        Origins:
          -
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
            DomainName: !Join ['', [www., !If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], pollin8.org.au, .s3-website-, Ref: theregion, .amazonaws.com]]
            Id: !Join ['', [S3-Website-www., !If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], pollin8.org.au, .s3-website-, Ref: theregion, .amazonaws.com]]
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:819017055465:certificate/919fc55a-7423-46a9-97bc-68c88d4a9fd3
          SslSupportMethod: sni-only
  wwwdns:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt cfdistro.DomainName
      HostedZoneName: pollin8.org.au.
      Name: !Join ['', [www., !If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], pollin8.org.au, .]]
      Type: A
  apexdns:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        HostedZoneId: Z2F56UZL2M1ACD # us-west-1
        DNSName: !Join ['', [s3-website-, Ref: theregion, .amazonaws.com]]
      HostedZoneName: pollin8.org.au.
      Name: !Join ['', [!If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], pollin8.org.au, .]]
      Type: A
  wwwbucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ['', [www., !If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], pollin8.org.au]]
      WebsiteConfiguration:
        IndexDocument: index.html
        RoutingRules:
          -
            RoutingRuleCondition:
              KeyPrefixEquals: config-module.js
            RedirectRule:
              Protocol: https
              HostName: !Join ['', [api-user., !If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], pollin8.org.au]]
              ReplaceKeyWith: config-module.js
  apexbucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ['', [!If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], pollin8.org.au]]
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Join ['', [www., !If [IsProd, !Ref "AWS::NoValue", !Ref envlevel], pollin8.org.au]]
          Protocol: http
